### ISSUE TITLE
Weird scaling issue with FeatDepotPriority

### ISSUE THREAD

**Issue by maldonadojuan** [akarnokd/plan-b-terraform-mods#1]
Hello, thank you for these mods! There seems to be a random scaling issue with some of the depots. I cannot replicate which depot has the issue, but sometimes a random depot will have an extremely large label when you zoom out of the planet. It seems to be connected to the label being placed away from the depot. I can lessen the issue by changing the OverlayFontScale to 0 but the label is still located away from the depot's location.

**Comment by akarnokd** [comment]
Hi. Thanks for the report.

Yeah, labels look bad when zoomed out. They are supposed to be hidden in the whole planet view. I'll work out a fix shortly.

**Comment by akarnokd** [comment]
Thanks again for the report and being the very first reporter.

The issue should be now fixed with **1.0.0.1**.

**Comment by maldonadojuan** [comment]
Thank you so much for the insanely fast turn around. These mods have really increased the QOL of this game!

**Comment by volkanogretmen** [comment]
I was about to report the same thing, thanks!
