### ISSUE TITLE
FeatProductionStats background alignment

### ISSUE THREAD

**Issue by volkanogretmen** [akarnokd/plan-b-terraform-mods#4]
![image](https://user-images.githubusercontent.com/25029377/219415456-50950dd5-f882-4d80-a0f1-95ce04dc4358.png)

1920x1080 fullscreen
110% UI scale
AA = off
FPS = 120

**Comment by volkanogretmen** [comment]
First image is directly after first game starts.
Below image is after having actual statistics.
![image](https://user-images.githubusercontent.com/25029377/219419442-5db1e925-aa10-4543-9757-e37234fada1d.png)

**Comment by akarnokd** [comment]
Does it happen only at 110%?
Please post the `Player.log` from `%USERPROFILE%\AppData\LocalLow\Gaddy Games\Plan B Terraform`.

**Comment by volkanogretmen** [comment]
Haven't tested it yet at different scales. Will post the results later tonight.

**Comment by akarnokd** [comment]
Does it happen when you start a new planet after exiting to the main menu from a save?

**Comment by volkanogretmen** [comment]
Ok, I managed to reproduce the issue.
Note: I have all mods enabled.

1. Clean start the game
2. Play > New Planet
3. Set all sliders to max, except for planets (keep that on 10), see image below.
![image](https://user-images.githubusercontent.com/25029377/219459706-07c29501-eb72-4cd4-962b-791d045e6a5e.png)

4. Confirm
5. Place a few extractors and depots down so the statistics screen populates data
6. The statistics screen is correctly shown
7. Quit the game
8. Re-do steps 2 to 5
9. Now, the statistics screen is bugged

So my guess is that at first, the screen is correctly shown, but at the second initalization, it somehow messes up the style of the screen and in some cases also shows default data, like the image below.

![Screenshot_20230216_165652](https://user-images.githubusercontent.com/25029377/219460557-d5ac4d32-206f-4fbd-89a5-3f03bb11bc4c.png)

Edit:
I think it would also be more cleaner to remove buildings (like extractors and factories) from the statistics screen and only show actual items that are being consumed by other buildings.

**Comment by volkanogretmen** [comment]
[Player.log](https://github.com/akarnokd/plan-b-terraform-mods/files/10759692/Player.log)

**Comment by akarnokd** [comment]
Thanks for the report. I released a fix for it.
