### ISSUE TITLE
Sudden have 438 trucks before having produced even a single one

### ISSUE THREAD

**Issue by shivan2418** [akarnokd/plan-b-terraform-mods#5]
So I cannot be 1000% that it is caused by any of these mods. But I did play until trucks twice before and did not observe this problem. The I started a new save with the mods listed below.
Sudden when I got trucks, I noticed I had more than 400 of them, although I had not produced a single one yet. Could it be related to the production limiter?

* [Add City Names](https://github.com/akarnokd/plan-b-terraform-mods#add-city-names) - Customize the selection of city names the game will use to generate the map.
* [City Population Label](https://github.com/akarnokd/plan-b-terraform-mods#city-population-label) - Display the population number underneath the city label in the main view and/or minimap.
* [Depot Priority](https://github.com/akarnokd/plan-b-terraform-mods#depot-priority) - Set priorities on depots so containers will be force-transferred towards higher priority depots.
* [Disable Building](https://github.com/akarnokd/plan-b-terraform-mods#disable-building) - Enable and disable production buildings via a on-screen button or keyboard shortcut.
* [Go to Exhausted Extractors](https://github.com/akarnokd/plan-b-terraform-mods#go-to-exhausted-extractors) - Shows a blinking panel (bottom left) if there are any extractors that have run out of minable ore.
* [Hotbar](https://github.com/akarnokd/plan-b-terraform-mods#hotbar) - Adds a bar at the bottom of the screen with 3 subpanels and 9 slots each for quickly selecting a building to be built.
* [Production Limiter](https://github.com/akarnokd/plan-b-terraform-mods#production-limiter) - Limit the production items that go into the global storage.
* [Production Statistics](https://github.com/akarnokd/plan-b-terraform-mods#production-statistics) - Show the production and consumption speed of items.

**Comment by akarnokd** [comment]
None of my mods add items like that and they live update the current numbers. Could you post a screenshot how you see the excess trucks?

**Comment by akarnokd** [comment]
Also there was a bug that made the Stats screen garbled up when switching saves, but no actual change to truck numbers.

**Comment by volkanogretmen** [comment]
To add to this (I was the one reporting the stats screen bug), I noticed that the stats screen takes information from previous saves. So I would have made 3 iron extractors as a test, started a new game and those 3 were displaying in the stats in the new game. 
So perhaps the 400 trucks displayed were from your previous save?

**Comment by volkanogretmen** [comment]
I managed to reproduce the issue:

1. Clean start the game
2. Play > New Planet
3. Place extractors and depot on IRON
4. You will get output below:
![Screenshot_20230217_160722](https://user-images.githubusercontent.com/25029377/219691897-f0b3a8f0-300b-40f2-8abc-e659bc0e2c35.png)
5. Close the game
6. Play > New Planet
7. Place some extractors and depot on SULFUR (nothing on IRON)
8. You will see the output below:
![Screenshot_20230217_160826](https://user-images.githubusercontent.com/25029377/219692280-5df8d9f4-a9ff-4fe7-a4ae-14fcccc7ea0b.png)

My guess is that the statistics are being cashed somewhere and not cleared inbetween games?

**Comment by akarnokd** [comment]
Thanks @volkanogretmen, fixed it.

@shivan2418 Was this your issue?

**Comment by shivan2418** [comment]
The trucks are real and I can place them, its not a UI bug. 
Ill try to start another save and see if it happens again.

![image](https://user-images.githubusercontent.com/40603805/219700332-ba2e0832-8b56-4033-b4f7-fdde600a810d.png)
![image](https://user-images.githubusercontent.com/40603805/219700494-b8b50785-ab62-49ea-9f5e-14161f7896d8.png)

**Comment by akarnokd** [comment]
Does this happen only if you change saves without quitting to desktop?

It could be this vanilla bug, https://trello.com/c/FMuUnrfd. If it was a caching bug, like the one above, the game wouldn't let you place and use them afaik.

**Comment by shivan2418** [comment]
I think it might be a vanilla caching bug. 
I just started a new save and now I have 202 trucks. Its basically how many I have had after placing in the example above.

![image](https://user-images.githubusercontent.com/40603805/219705567-25d3fc38-59d3-45eb-b134-2c22f1859668.png)

**Comment by akarnokd** [comment]
Very weird. Is it only trucks, never depots or factories carrying over?

**Comment by shivan2418** [comment]
Does not seem like it. 
But if there is a bug in vanilla then its not your mod thats the problem then? 
Just don't get why I havnt had it before. Maybe I just had too few saves.

**Comment by akarnokd** [comment]
No idea. Only way to rule out my mods is to try reproducing the issue without them.

**Comment by akarnokd** [comment]
The extra trucks are a vanilla bug. It should be fixed in the next release (already fixed in beta).

https://discord.com/channels/321299004778479617/1062417211882479756/1076460223524524035
