### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by domesticated** [akarnokd/plan-b-terraform-mods#6]
I followed the instructions exactly and it's not working for me.

Here's the error I get:

[Message:   BepInEx] BepInEx 5.4.21.0 - Plan B Terraform (2/18/2023 12:42:18 AM)
[Info   :   BepInEx] Running under Unity v2021.3.14.15655304
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete

Screenshot of plugins in the correct folder: https://ibb.co/D1HhyhD

**Comment by domesticated** [comment]
Got it working.

**Comment by domesticated** [comment]
Got it working

**Comment by akarnokd** [comment]
You have to use the various `zip`s, not download the source code.
