### ISSUE TITLE
I cant get the vehicle speed to work :/

### ISSUE THREAD

**Issue by Valoneu** [akarnokd/plan-b-terraform-mods#7]
title

**Comment by akarnokd** [comment]
How is it not working?

**Comment by Valoneu** [comment]
it does not speed up the vehicles, also the drones are just normal or insanely sped up for me, or do i need new save?

**Comment by akarnokd** [comment]
Did you install the mod correctly?

**Comment by Valoneu** [comment]
yes other mods work and the speedup for miners and factories

**Comment by Valoneu** [comment]
or how big of a number do i need to put there
i tried like 2 then 200 and then 200000 and it did nothing for everyone

**Comment by akarnokd** [comment]
No need for new save. You'll have to play with the numbers. I use 6-10 for vehicle speed and 10-20 for drone speeds.

**Comment by Valoneu** [comment]
could you copy your config here?

**Comment by akarnokd** [comment]
Just set the drone speed to 15 and the vehicle speeds to 6.

**Comment by Valoneu** [comment]
which vehicle speed all of them?

**Comment by akarnokd** [comment]
Yes.

**Comment by Valoneu** [comment]
ok will try :)

**Comment by Valoneu** [comment]
ok now it works on some of the trucks and sometimes they are too fast to unload

**Comment by akarnokd** [comment]
Can't do much about it, a lot of it is dependent how the vanilla was calibrated. Hence you need to play with the numbers.
